add missing import
Fix this:

  File "passerd/scheduler.py", line 143, in wait_rate_limit
      delay = int(self.api.rate_limit_reset - time.time())
  NameError: global name 'time' is not defined

Signed-off-by: Eduardo Habkost <ehabkost@raisama.net>